import js from '@eslint/js';
import globals from 'globals';
import stylistic from '@stylistic/eslint-plugin';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            sourceType: 'script',
            parserOptions: {
                ecmaFeatures: {
                    globalReturn: true,
                },
            },
            globals: {
                ...globals.browser,
                ...globals.jquery,
                ...globals.greasemonkey,
            },
        },
        plugins: {
            '@stylistic': stylistic,
        },
        rules: {
            // === Code-quality rules (migrated from .eslintrc) ===
            'accessor-pairs': ['error'],
            'array-callback-return': ['error'],
            'arrow-body-style': ['error'],
            'block-scoped-var': ['error'],
            'consistent-return': ['error'],
            'consistent-this': ['error'],
            'curly': ['error'],
            'default-param-last': ['error'],
            'dot-notation': ['error'],
            'eqeqeq': ['error', 'always'],
            'func-name-matching': ['error'],
            'func-names': ['error'],
            'func-style': ['error', 'declaration', {
                allowArrowFunctions: true,
            }],
            'grouped-accessor-pairs': ['error', 'getBeforeSet'],
            'max-classes-per-file': ['error'],
            'max-depth': ['error', 5],
            'max-nested-callbacks': ['error', 5],
            'no-alert': ['error'],
            'no-array-constructor': ['error'],
            'no-caller': ['error'],
            'no-constructor-return': ['error'],
            'no-duplicate-imports': ['error'],
            'no-else-return': ['error'],
            'no-empty-function': ['error'],
            'no-eval': ['error'],
            'no-extend-native': ['error'],
            'no-implicit-coercion': ['error'],
            'no-implied-eval': ['error'],
            'no-invalid-this': ['error'],
            'no-iterator': ['error'],
            'no-labels': ['error'],
            'no-lone-blocks': ['error'],
            'no-lonely-if': ['error'],
            'no-loop-func': ['error'],
            'no-multi-assign': ['error'],
            'no-multi-str': ['error'],
            'no-negated-condition': ['error'],
            'no-nested-ternary': ['error'],
            'no-new-func': ['error'],
            'no-new-object': ['error'],
            'no-new-wrappers': ['error'],
            'no-new': ['error'],
            'no-octal-escape': ['error'],
            'no-proto': ['error'],
            'no-return-assign': ['error'],
            'no-return-await': ['error'],
            'no-script-url': ['error'],
            'no-self-compare': ['error'],
            'no-sequences': ['error'],
            'no-template-curly-in-string': ['error'],
            'no-undef-init': ['error'],
            'no-unneeded-ternary': ['error', {
                defaultAssignment: false,
            }],
            'no-unused-expressions': ['error'],
            'no-unused-vars': ['error', {
                caughtErrors: 'all',
                caughtErrorsIgnorePattern: '^unused($|[A-Z].*$)',
                argsIgnorePattern: '^unused($|[A-Z].*$)',
                varsIgnorePattern: '^unused($|[A-Z].*$)',
            }],
            'no-use-before-define': ['error'],
            'no-useless-call': ['error'],
            'no-useless-computed-key': ['error'],
            'no-useless-concat': ['error'],
            'no-useless-constructor': ['error'],
            'no-useless-rename': ['error'],
            'no-useless-return': ['error'],
            'no-var': ['error'],
            'no-void': ['error'],
            'object-shorthand': ['error'],
            'one-var': ['error', 'never'],
            'operator-assignment': ['error'],
            'prefer-arrow-callback': ['error', {
                allowNamedFunctions: true,
            }],
            'prefer-destructuring': ['error', {
                array: false,
                object: true,
            }],
            'prefer-exponentiation-operator': ['error'],
            'prefer-numeric-literals': ['error'],
            'prefer-object-spread': ['error'],
            'prefer-promise-reject-errors': ['error'],
            'prefer-regex-literals': ['error'],
            'prefer-rest-params': ['error'],
            'prefer-spread': ['error'],
            'prefer-template': ['error'],
            'radix': ['error', 'as-needed'],
            'sort-imports': ['error'],
            'symbol-description': ['error'],
            'unicode-bom': ['error'],
            'vars-on-top': ['error'],
            'yoda': ['error'],

            // === Stylistic rules (@stylistic plugin) ===
            '@stylistic/indent': ['error', 4, { SwitchCase: 1 }],
            '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
            '@stylistic/semi': ['error', 'always'],
            '@stylistic/comma-dangle': ['error', 'always-multiline'],
            '@stylistic/no-trailing-spaces': ['error'],
            '@stylistic/eol-last': ['error'],
            '@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
        },
    },
];
